import type { BeatRow, LicenseTierRow, VideoRow } from "@/lib/data/types";

const t = "2026-01-01T00:00:00.000Z";

/** Demo catalog for local dev without a database (aligned with supabase/seed.sql). */
export const STATIC_LICENSE_TIERS: LicenseTierRow[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    slug: "basic",
    name: "Basic",
    description: "MP3, distribution limits per license agreement.",
    price_cents: 5999,
    rights_json: null,
    sort_order: 1,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    slug: "premium",
    name: "Premium",
    description: "MP3 + WAV, higher caps.",
    price_cents: 9999,
    rights_json: null,
    sort_order: 2,
    is_highlighted: true,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    slug: "premium-trackouts",
    name: "Premium + Trackouts",
    description: "WAV + stems / trackouts.",
    price_cents: 17999,
    rights_json: null,
    sort_order: 3,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    slug: "exclusive",
    name: "Exclusive",
    description: "Exclusive purchase; terms finalized at sale.",
    price_cents: 200000,
    rights_json: null,
    sort_order: 4,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
];

export const STATIC_BEATS: BeatRow[] = [
  {
    id: "22222222-2222-2222-2222-222222222201",
    slug: "midnight-run",
    title: "Midnight Run",
    description: "Dark trap with cinematic pads.",
    bpm: 140,
    musical_key: "F# min",
    genre: "Dark Trap",
    mood: ["drill", "cinematic"],
    is_active: true,
    is_featured: true,
    artwork_path: "images/beats/midnight-run.jpg",
    preview_path: null,
    duration_seconds: 158,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222202",
    slug: "neon-drift",
    title: "Neon Drift",
    description: "Bouncy west-coast inspired groove.",
    bpm: 97,
    musical_key: "A min",
    genre: "Melodic",
    mood: ["westcoast", "bouncy"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/neon-drift.jpg",
    preview_path: null,
    duration_seconds: 185,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222203",
    slug: "signal-lost",
    title: "Signal Lost",
    description: "Smooth R&B bounce.",
    bpm: 88,
    musical_key: "D maj",
    genre: "R&B",
    mood: ["smooth", "vibes"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/signal-lost.jpg",
    preview_path: null,
    duration_seconds: 172,
    created_at: t,
    updated_at: t,
  },
];

export const STATIC_VIDEOS: VideoRow[] = [
  {
    id: "33333333-3333-3333-3333-333333333301",
    title: "Studio session: building the drop",
    artist: "HiveMind",
    thumbnail_path: null,
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    category: "tutorial",
    tags: ["studio", "tutorial"],
    is_featured: true,
    linked_beat_id: null,
    sort_order: 1,
    created_at: t,
  },
  {
    id: "33333333-3333-3333-3333-333333333302",
    title: "Type beat walkthrough",
    artist: "HiveMind",
    thumbnail_path: null,
    embed_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    category: "type beat",
    tags: ["type beat"],
    is_featured: false,
    linked_beat_id: null,
    sort_order: 2,
    created_at: t,
  },
];
