import type { BeatRow, LicenseTierRow, VideoRow } from "@/lib/data/types";

const t = "2026-01-01T00:00:00.000Z";

/** Demo catalog for local dev without a database (aligned with supabase/seed.sql). */
export const STATIC_LICENSE_TIERS: LicenseTierRow[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    slug: "basic",
    name: "Basic",
    description: "MP3, distribution limits per license agreement.",
    price_cents: 4999,
    rights_json: null,
    sort_order: 1,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    slug: "premium",
    name: "Premium",
    description: "MP3 + WAV, higher caps.",
    price_cents: 6999,
    rights_json: null,
    sort_order: 2,
    is_highlighted: true,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    slug: "premium-trackouts",
    name: "Premium + Trackouts",
    description: "WAV + stems / trackouts.",
    price_cents: 14999,
    rights_json: null,
    sort_order: 3,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    slug: "exclusive",
    name: "Exclusive",
    description: "Exclusive purchase; terms finalized at sale.",
    price_cents: 100000,
    rights_json: null,
    sort_order: 4,
    is_highlighted: false,
    created_at: t,
    updated_at: t,
  },
];

export const STATIC_BEATS: BeatRow[] = [
  {
    id: "22222222-2222-2222-2222-222222222201",
    slug: "midnight-run",
    title: "Midnight Run",
    description: "Dark trap with cinematic pads.",
    bpm: 140,
    musical_key: "F# min",
    genre: "Dark Trap",
    mood: ["drill", "cinematic"],
    is_active: true,
    is_featured: true,
    artwork_path: "images/beats/midnight-run.jpg",
    preview_path: null,
    duration_seconds: 158,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222202",
    slug: "neon-drift",
    title: "Neon Drift",
    description: "Bouncy west-coast inspired groove.",
    bpm: 97,
    musical_key: "A min",
    genre: "Melodic",
    mood: ["westcoast", "bouncy"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/neon-drift.jpg",
    preview_path: null,
    duration_seconds: 185,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222203",
    slug: "signal-lost",
    title: "Signal Lost",
    description: "Smooth R&B bounce.",
    bpm: 88,
    musical_key: "D maj",
    genre: "R&B",
    mood: ["smooth", "vibes"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/signal-lost.jpg",
    preview_path: null,
    duration_seconds: 172,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222204",
    slug: "chrome-rain",
    title: "Chrome Rain",
    description: "Placeholder — melodic drill bounce.",
    bpm: 144,
    musical_key: "G min",
    genre: "Drill",
    mood: ["melodic", "bounce"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/midnight-run.jpg",
    preview_path: null,
    duration_seconds: 168,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222205",
    slug: "void-walk",
    title: "Void Walk",
    description: "Placeholder — wide pads, heavy low end.",
    bpm: 132,
    musical_key: "D# min",
    genre: "Dark Trap",
    mood: ["cinematic", "wide"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/neon-drift.jpg",
    preview_path: null,
    duration_seconds: 195,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222206",
    slug: "glass-ceiling",
    title: "Glass Ceiling",
    description: "Placeholder — airy synths, crisp hats.",
    bpm: 150,
    musical_key: "A min",
    genre: "Trap",
    mood: ["airy", "crisp"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/signal-lost.jpg",
    preview_path: null,
    duration_seconds: 181,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222207",
    slug: "redline-hush",
    title: "Redline Hush",
    description: "Placeholder — uptempo pocket shuffle.",
    bpm: 160,
    musical_key: "E min",
    genre: "Drill",
    mood: ["uptempo", "shuffle"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/midnight-run.jpg",
    preview_path: null,
    duration_seconds: 154,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222208",
    slug: "after-midnight",
    title: "After Midnight",
    description: "Placeholder — late-night R&B groove.",
    bpm: 82,
    musical_key: "F maj",
    genre: "R&B",
    mood: ["late", "smooth"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/neon-drift.jpg",
    preview_path: null,
    duration_seconds: 204,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222209",
    slug: "low-tide",
    title: "Low Tide",
    description: "Placeholder — laid-back coastal bounce.",
    bpm: 94,
    musical_key: "C min",
    genre: "Melodic",
    mood: ["laid-back", "coastal"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/signal-lost.jpg",
    preview_path: null,
    duration_seconds: 176,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222210",
    slug: "ice-palace",
    title: "Ice Palace",
    description: "Placeholder — cold bells, sliding 808s.",
    bpm: 138,
    musical_key: "B min",
    genre: "Trap",
    mood: ["cold", "sliding"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/midnight-run.jpg",
    preview_path: null,
    duration_seconds: 189,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222211",
    slug: "north-star",
    title: "North Star",
    description: "Placeholder — anthem hook pocket.",
    bpm: 128,
    musical_key: "G min",
    genre: "Hip-Hop",
    mood: ["anthem", "hook"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/neon-drift.jpg",
    preview_path: null,
    duration_seconds: 198,
    created_at: t,
    updated_at: t,
  },
  {
    id: "22222222-2222-2222-2222-222222222212",
    slug: "heavy-air",
    title: "Heavy Air",
    description: "Placeholder — dense layers, slow burn.",
    bpm: 70,
    musical_key: "D min",
    genre: "Boom Bap",
    mood: ["dense", "slow"],
    is_active: true,
    is_featured: false,
    artwork_path: "images/beats/signal-lost.jpg",
    preview_path: null,
    duration_seconds: 223,
    created_at: t,
    updated_at: t,
  },
];

export const STATIC_VIDEOS: VideoRow[] = [
  {
    id: "33333333-3333-3333-3333-333333333301",
    title: "Music video",
    artist: "HiveMind",
    thumbnail_path: null,
    embed_url: "https://www.youtube.com/embed/pSk9Q_iPHjM",
    category: "music video",
    tags: ["official"],
    is_featured: true,
    linked_beat_id: null,
    sort_order: 1,
    created_at: t,
  },
  {
    id: "33333333-3333-3333-3333-333333333302",
    title: "Music video",
    artist: "HiveMind",
    thumbnail_path: null,
    embed_url: "https://www.youtube.com/embed/33Y1AyjYOeU",
    category: "music video",
    tags: ["official"],
    is_featured: false,
    linked_beat_id: null,
    sort_order: 2,
    created_at: t,
  },
];
