create table if not exists public.beat_store_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('preview', 'add_to_cart')),
  beat_slug text not null references public.beats(slug) on delete cascade,
  session_id text,
  page_path text,
  user_agent text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_beat_store_events_created_at
  on public.beat_store_events (created_at desc);

create index if not exists idx_beat_store_events_event_type
  on public.beat_store_events (event_type);

create index if not exists idx_beat_store_events_beat_slug
  on public.beat_store_events (beat_slug);

alter table public.beat_store_events enable row level security;

drop policy if exists "beat_store_events_insert_public" on public.beat_store_events;
create policy "beat_store_events_insert_public" on public.beat_store_events
  for insert
  with check (true);

drop policy if exists "beat_store_events_select_admin" on public.beat_store_events;
create policy "beat_store_events_select_admin" on public.beat_store_events
  for select to authenticated
  using (public.is_admin());
